import { QuizConfig } from '../models/quiz.types'

export const QUIZ_CONFIG: QuizConfig = {
  startScreenId: 'welcome',
  screens: {
    welcome: {
      id: 'welcome',
      kind: 'welcome',
      titleKey: 'screens.welcome.titleLine1',
      subtitleKey: 'screens.welcome.subtitle',
      continueLabelKey: 'common.getStarted',
      showBack: false,
      branch: { type: 'static', target: 'experience-level' },
    },
    'experience-level': {
      id: 'experience-level',
      kind: 'single-select',
      titleKey: 'screens.experienceLevel.title',
      track: 'standard',
      progress: { current: 1, total: 3 },
      segmentedProgress: { total: 4, activeIndex: 0 },
      showBack: true,
      options: [
        {
          id: 'beginner',
          labelKey: 'options.experience.beginner.label',
          descriptionKey: 'options.experience.beginner.description',
        },
        {
          id: 'intermediate',
          labelKey: 'options.experience.intermediate.label',
          descriptionKey: 'options.experience.intermediate.description',
        },
        {
          id: 'advanced',
          labelKey: 'options.experience.advanced.label',
          descriptionKey: 'options.experience.advanced.description',
        },
      ],
      branch: {
        type: 'answer',
        questionId: 'experience-level',
        map: {
          advanced: 'expertise',
          beginner: 'inspiration',
          intermediate: 'inspiration',
        },
      },
    },
    inspiration: {
      id: 'inspiration',
      kind: 'inspiration',
      titleKey: 'screens.inspiration.title',
      track: 'standard',
      showBack: true,
      continueLabelKey: 'common.continue',
      segmentedProgress: { total: 4, activeIndex: 1 },
      branch: { type: 'static', target: 'interests' },
    },
    interests: {
      id: 'interests',
      kind: 'multi-select',
      titleKey: 'screens.interests.title',
      track: 'standard',
      progress: { current: 2, total: 3 },
      segmentedProgress: { total: 4, activeIndex: 2 },
      showBack: true,
      continueLabelKey: 'common.continue',
      options: [
        {
          id: 'design',
          labelKey: 'options.interests.design.label',
          descriptionKey: 'options.interests.design.description',
        },
        {
          id: 'development',
          labelKey: 'options.interests.development.label',
          descriptionKey: 'options.interests.development.description',
        },
        {
          id: 'strategy',
          labelKey: 'options.interests.strategy.label',
          descriptionKey: 'options.interests.strategy.description',
        },
      ],
      branch: {
        type: 'priority',
        questionId: 'interests',
        priority: ['design', 'development', 'strategy'],
        map: {
          design: 'design-preference',
          development: 'technical-focus',
          strategy: 'primary-objective',
        },
      },
    },
    'design-preference': {
      id: 'design-preference',
      kind: 'single-select',
      titleKey: 'screens.designPreference.title',
      track: 'standard',
      progress: { current: 3, total: 3 },
      segmentedProgress: { total: 4, activeIndex: 3 },
      showBack: true,
      options: [
        {
          id: 'solo-designer',
          labelKey: 'options.designPreference.soloDesigner.label',
          descriptionKey: 'options.designPreference.soloDesigner.description',
        },
        {
          id: 'team-collaboration',
          labelKey: 'options.designPreference.teamCollaboration.label',
          descriptionKey: 'options.designPreference.teamCollaboration.description',
        },
      ],
      branch: { type: 'static', target: 'standard-completion' },
    },
    'technical-focus': {
      id: 'technical-focus',
      kind: 'single-select',
      titleKey: 'screens.technicalFocus.title',
      track: 'standard',
      progress: { current: 3, total: 3 },
      segmentedProgress: { total: 4, activeIndex: 3 },
      showBack: true,
      options: [
        {
          id: 'frontend',
          labelKey: 'options.technicalFocus.frontend.label',
          descriptionKey: 'options.technicalFocus.frontend.description',
        },
        {
          id: 'backend',
          labelKey: 'options.technicalFocus.backend.label',
          descriptionKey: 'options.technicalFocus.backend.description',
        },
      ],
      branch: { type: 'static', target: 'standard-completion' },
    },
    'primary-objective': {
      id: 'primary-objective',
      kind: 'single-select',
      titleKey: 'screens.primaryObjective.title',
      track: 'standard',
      progress: { current: 3, total: 3 },
      segmentedProgress: { total: 4, activeIndex: 3 },
      showBack: true,
      options: [
        {
          id: 'growth',
          labelKey: 'options.primaryObjective.growth.label',
          descriptionKey: 'options.primaryObjective.growth.description',
        },
        {
          id: 'efficiency',
          labelKey: 'options.primaryObjective.efficiency.label',
          descriptionKey: 'options.primaryObjective.efficiency.description',
        },
      ],
      branch: { type: 'static', target: 'standard-completion' },
    },
    'standard-completion': {
      id: 'standard-completion',
      kind: 'completion',
      titleKey: 'screens.standardCompletion.title',
      subtitleKey: 'screens.standardCompletion.subtitle',
      track: 'standard',
      showBack: true,
      continueLabelKey: 'common.submit',
      branch: { type: 'terminal' },
    },
    expertise: {
      id: 'expertise',
      kind: 'single-select',
      titleKey: 'screens.expertise.title',
      track: 'advanced',
      progress: { current: 1, total: 2, label: 'advanced' },
      segmentedProgress: { total: 2, activeIndex: 0 },
      showBack: true,
      options: [
        {
          id: 'system-architecture',
          labelKey: 'options.expertise.systemArchitecture.label',
          descriptionKey: 'options.expertise.systemArchitecture.description',
        },
        {
          id: 'technical-leadership',
          labelKey: 'options.expertise.technicalLeadership.label',
          descriptionKey: 'options.expertise.technicalLeadership.description',
        },
        {
          id: 'research-innovation',
          labelKey: 'options.expertise.researchInnovation.label',
          descriptionKey: 'options.expertise.researchInnovation.description',
        },
      ],
      branch: { type: 'static', target: 'achievement' },
    },
    achievement: {
      id: 'achievement',
      kind: 'single-select',
      titleKey: 'screens.achievement.title',
      track: 'advanced',
      progress: { current: 2, total: 2, label: 'advanced' },
      segmentedProgress: { total: 2, activeIndex: 1 },
      showBack: true,
      options: [
        {
          id: 'maximize-impact',
          labelKey: 'options.achievement.maximizeImpact.label',
          descriptionKey: 'options.achievement.maximizeImpact.description',
        },
        {
          id: 'deep-mastery',
          labelKey: 'options.achievement.deepMastery.label',
          descriptionKey: 'options.achievement.deepMastery.description',
        },
        {
          id: 'drive-innovation',
          labelKey: 'options.achievement.driveInnovation.label',
          descriptionKey: 'options.achievement.driveInnovation.description',
        },
      ],
      branch: { type: 'static', target: 'advanced-completion' },
    },
    'advanced-completion': {
      id: 'advanced-completion',
      kind: 'advanced-completion',
      titleKey: 'screens.advancedCompletion.title',
      subtitleKey: 'screens.advancedCompletion.subtitle',
      track: 'advanced',
      showBack: true,
      continueLabelKey: 'common.submit',
      resourceBulletKeys: [
        'screens.advancedCompletion.bullet1',
        'screens.advancedCompletion.bullet2',
        'screens.advancedCompletion.bullet3',
      ],
      branch: { type: 'terminal' },
    },
  },
}
